print("Hello Python3:The Hard Way!")
print("Hello Again")
print("I like typing this.")
print("This is fun!")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
